@startuml
'https://plantuml.com/class-diagram
class Menu

class Estadisticas {
    - size_t fuerza
    - size_t defensa
    - size_t velocidad
    - size_t poder
    - Menu menu

    + Estadisticas(const size_t &fuerza, const size_t &defensa, const size_t &velocidad)
    + void aplicar_bonificacion()
    + size_t obtener_fuerza()
    + size_t obtener_defensa()
    + size_t obtener_velocidad()
    + size_t obtener_poder()
    + void mostrar()
    + static std::ostream& operator<<(std::ostream &os, const Estadisticas &estadisticas)
}

' Relaciones
Estadisticas *-- Menu : "composición"

@enduml