@startuml
'https://plantuml.com/class-diagram

class Juego {
    - Protagonista protagonista
    - Menu menu
    - BovedaCristales boveda
    - FusionadorEnergon fusionador
    - bool juego_en_curso
    - std::string nombre_jugador
    - AdministradorTransformers administrador_transformers
    - TablaClasificacion tabla_clasificacion

    + Juego()
    + void procesar_menu_principal(&opcion_menu : const char,  &nombre : const std::string)
    + bool jugando() const
    + void respuesta_personaje(&mensaje : const std::string)
    + void manejar_sugerencia_personaje()
    + void manejar_opcion_escribir_mensaje()
    + void manejar_cambiar_estado()
    + void fusionador_de_cristales(const int &entrada_1, const int &entrada_2)
    + void manejar_fusionar_de_cristales()
    + void manejar_de_almacenamiento_de_cristales()
    + void mostrar_boveda()
    + void manejar_exportar_boveda(std::string &ruta)
    + void manejar_de_bodega_mostrar_tamanio()
    + void manejar_equipar_un_cristal()
    + void mostrar_cantidad_cristales_equipados()
    + void manejar_boveda()
    + std::string convertir_faccion_string(const int &faccion)
    + void manejar_crear_transformers()
    + void manejar_buscar_transformers()
    + void manejar_eliminar_transformers()
    + void manejar_transformar()
    + void mostrar_transformers_secundarios()
    + std::string solicitar_nombre_transformers()
    + int solicitar_vehiculo(const int& faccion)
    + int solicitar_faccion()
    + std::string convertir_vehiculo_string(const int& vehiculo)
    + void manejar_agregar_transformers(const std::string &nombre, const int &fuerza, const int &defensa, const int &velocidad, const std::string &faccion, const std::string &vehiculo)
    + void crear_transformers(std::string nombre, int tipo_vehiculo)
    + void manejar_crear_autobots(const std::string& nombre)
    + void manejar_crear_decepticons(const std::string& nombre)
    + void manejar_flujo_juego_principal()
    + bool verificar_entrada_del_cristal(const int &entrada)
    + void manejar_administrar_transformers()
    + void manejar_interactuar_con_el_personaje()
    + void mostrar_tabla_clasificacion()
    + int calcular_estadistica(int estadistica_base)
}

' Relaciones
Juego --> Protagonista : "usa"
Juego --> Menu : "usa"
Juego --> BovedaCristales : "contiene"
Juego --> FusionadorEnergon : "usa"
Juego --> AdministradorTransformers : "usa"
Juego --> TablaClasificacion : "usa"
Juego --> Utilidades : "usa"

@enduml