@startuml
'https://plantuml.com/class-diagram

class Utilidades

class ManejadorDeRespuestas {
    - std::string respuestas[MAX_RESPUESTAS]
    - std::string respuestas_random[MAX_RESPUESTAS]
    - int cantidad_respuestas
    - int cantidad_respuestas_random
    - Utilidades utilidades

    + ManejadorDeRespuestas()
    + void agregar_respuesta(respuesta : const string&)
    + void agregar_respuesta_random(respuesta_random : const string&)
    + std::string obtener_respuesta_por_indice(indice : const int&)
    + std::string obtener_respuesta_random()
}

' Relaciones
ManejadorDeRespuestas --> Utilidades : "usa"

@enduml