@startuml
'https://plantuml.com/class-diagram

class Utilidades

class ManejadorDePalabrasClaves {
    - std::string palabras_claves[MAX_PALABRAS_CLAVES]
    - int cantidad_palabras_claves
    - Utilidades utilidades

    + ManejadorDePalabrasClaves()
    + void agregar_palabras_clave(const std::string& palabra)
    + int buscar_palabras_clave(const std::string& cadena)
}

' Relaciones
ManejadorDePalabrasClaves *-- Utilidades : "composición"

@enduml