@startuml
'https://plantuml.com/class-diagram

enum TipoDeRespuesta {
    POR_PALABRA_CLAVE
    ALEATOREAMENTE
}

class ManejadorDeMensajes {
    - ManejadorDePalabrasClaves& manejador_palabras
    - ManejadorDeRespuestas& manejador_respuestas
    - int primera_palabra_clave_hallada

    + ManejadorDeMensajes(ManejadorDePalabrasClaves& manejador_palabras, ManejadorDeRespuestas& manejador_respuestas)
    + void procesar_mensajes(const std::string& mensaje)
    + void mostrar_mensajes(TipoDeRespuesta tipo)
}

class ManejadorDePalabrasClaves
class ManejadorDeRespuestas

' Relaciones
ManejadorDeMensajes --> ManejadorDePalabrasClaves : usa
ManejadorDeMensajes --> ManejadorDeRespuestas : usa
ManejadorDeMensajes ..> TipoDeRespuesta : utiliza

@enduml