@startuml
'https://plantuml.com/class-diagram

class Utilidades
class ManejadorDeRespuestas
class ManejadorDeMensajes
class ManejadorPalabrasClave

class Megatron {
    - Utilidades utilidades
    - int estado_de_intencion

    + Megatron()
    + void responder(std::string mensaje)
    + void sugerir_fusion()
    + void cambiar_intencion(std::string intencion)
}

' Relaciones
Megatron *-- Utilidades : "composición"
Megatron --> ManejadorDeMensajes : "depende"
Megatron --> ManejadorPalabrasClave : "depende"
Megatron --> ManejadorDeRespuestas : "depende"


@enduml