@startuml
'https://plantuml.com/class-diagram
class OptimusPrime
class Megatron
class BovedaCristales
class Transformers

class ExcepcionProtagonista {
    + ExcepcionProtagonista(mensaje : string)
    + ExcepcionProtagonista()
}

enum Personaje {
    MEGATRON,
    OPTIMUS_PRIME,
    PERSONAJE_INVALIDO
}

class Protagonista {
    - OptimusPrime optimus
    - Megatron megatron
    - Personaje personaje_jugando
    - BovedaCristales cristales_equipados
    - Transformers transformer_principal
    ---
    + Protagonista(personaje : Personaje)
    + void obtener_respuesta(mensaje : const string&)
    + void obtener_sugerencia()
    + Transformers obtener_transformer_principal()
    + void actualizar_estado(indice : const char&)
    + Personaje obtener_personaje()
    + void equipar_cristal(cristal : Cristal)
    + void ver_cristales_equipados()
    + size_t obtener_cantidad_cristales_equipados()
    - string obtener_estado(indice : const char&)
}

' Relaciones
Protagonista --> OptimusPrime : "usa"
Protagonista --> Megatron : "usa"
Protagonista --> BovedaCristales : "contiene"
Protagonista --> Personaje : "usa"
Protagonista --> Transformers : "usa"
Protagonista ..> ExcepcionProtagonista : "lanza"
@enduml